### ISSUE TITLE
Deleted codes cause error in `populateCodes()` for future queries

### ISSUE THREAD

**Issue by tcarrio** [csi4999-panic-button/panic-button#19]
When codes are deleted the middleware for `find` and `findOne` queries will cause a failure due to unmatched references on the Classroom `*code` ObjectId's having no existing reference in InviteCodes

**Comment by tcarrio** [comment]
This should be fixed if we switch over to allowing codes to exist forever.

**Comment by dyladan** [comment]
This is fixed now that codes are strings
